name: Hugo

on: [push]

jobs:
  build:
    strategy:
        matrix:
          image: [ext-ubuntu, alpine]
          source: [quickstart]
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        version: ${{ matrix.version }}
        image: ${{ matrix.image }}
        source: ${{ matrix.source }}
