name: Hugo

on: [push]

jobs:
  build:
    strategy:
        matrix:
          image: [ext-ubuntu]

          
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: hugo
      uses: klakegg/actions-hugo@1.0.0
      with:
        image: ${{ matrix.image }}
